apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-app
  namespace: chaos
  labels:
    app: chaos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-app
  template:
    metadata:
      labels:
        app: chaos-app
    spec:
      containers:
        - name: chaos-app
          image: nayza72/chaos-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: OLLAMA_API_URL
              value: "http://ollama-service:11434/api/chat"
            - name: OLLAMA_HOST
              value: "http://ollama-service:11434"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: chaos-service
  namespace: chaos
spec:
  type: NodePort
  selector:
    app: chaos-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30088
